name: CD Pipeline

on:
  push:
    branches:
      - main       # Only trigger CD when main is updated

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Trigger Databricks Job
        run: |
          curl -X POST "${{ secrets.DATABRICKS_HOST }}/api/2.1/jobs/run-now" \
          --header "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          --header "Content-Type: application/json" \
          -d "{\"job_id\": ${{ secrets.DATABRICKS_JOB_ID }}}"
